# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ee046b97bdd5e6cb000ffd32eb086c2467ae12fe25abb41f21c74bdae4ec1d8bb7c47f8deaa2af042570e5c993afbe757b011e77fcf55c54a51460b153e6a40

test:
  secret_key_base: 1bf6fd28c2ee39bad1a720580241ffe337745286bdcf688997f4b0ee13ddb52b6db1b6995f93b9583da95e644282c5581c18d8e3f036869dec242f56e141312d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
